### ISSUE TITLE
Error calling emptyBucket function.

### ISSUE THREAD

**Issue by xavier-thomas** [xavier-thomas/aws-cfn-stack-cleanup#9]
##### SUMMARY
When invoking the lambda against a bucket, it throws the following error
`Error during Cleanup - TypeError: Cannot read property 'emptyBucket' of undefined`

##### ISSUE TYPE
- Bug Report

##### VERSIONS

```paste below
v1.1.1 and v1.1.0
```

##### STEPS TO REPRODUCE

- Deploy the lambda from SAR
- Invoke the lambda from cloud formation
- Bucket to delete needs to have content, so that the empty bucket function is called.

**Comment by xavier-thomas** [comment]
@mfarrow701 Believe this is due to the use of `this.emptyBucket()`

https://github.com/xavier-thomas/aws-cfn-stack-cleanup/blob/master/src/s3.js#L63

Any alternatives here ?

**Comment by mfarrow701** [comment]
> @mfarrow701 Believe this is due to the use of `this.emptyBucket()`
> 
> https://github.com/xavier-thomas/aws-cfn-stack-cleanup/blob/master/src/s3.js#L63
> 
> Any alternatives here ?

@xavier-thomas 
You can call `await emptyBucket(srcBucket)` (line 68), and remove the function parameter `_emptyBucket = this.emptyBucket`, no?

**Comment by xavier-thomas** [comment]
> emptyBucket(srcBucket)

Because we are exporting `export const emptyBucket`, I don't believe it allows you to call it as a function.

**Comment by mfarrow701** [comment]
> > emptyBucket(srcBucket)
> 
> Because we are exporting `export const emptyBucket`, I don't believe it allows you to call it as a function.

@xavier-thomas, sure you can 😉 The `export` keyword just allows you to import, read or call the method from another module.

**Comment by xavier-thomas** [comment]
> > > emptyBucket(srcBucket)
> > 
> > 
> > Because we are exporting `export const emptyBucket`, I don't believe it allows you to call it as a function.
> 
> @xavier-thomas, sure you can 😉 The `export` keyword just allows you to import, read or call the method from another module.

And what's the best way of mocking this in the tests ? Since the tests are testing both functions separately. I need to mock the resolved value of emptyBucket() when called by the deleteBucket(). But the actual tests for the emptyBucket() should not mock the call.

I realise that I can mock all the api calls, but I would rather test each function in isolation.

**Comment by xavier-thomas** [comment]
@mfarrow701 Didn't have a lot of time to try the JS classes. Went instead with your option of splitting the modules. https://github.com/xavier-thomas/aws-cfn-stack-cleanup/pull/11

This should get it working (🤞) , but feel free to try the class approach.
